### ISSUE TITLE
CertificateError in 'ebics initialisation' step (ebics_init_1)

### ISSUE THREAD

**Issue by NMisko** [Noviat/account_ebics#21]
Happens when clicking on EBICS INITIALISATION for this one bank.
We have another bank set up, where we got past this step, so we believe it to be an issue with this one bank.

Do you have any idea what this could be due to? Unfortunately the errors all stem from within the fintech module and I can't find its source code. I'd appreciate any pointers.

```
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/account_ebics/models/ebics_userid.py", line 284, in ebics_init_1
    supported_versions = client.HEV()
  File "<frozen fintech.ebics>", line 1886, in HEV
  File "<frozen fintech.ebics>", line 3274, in send
  File "<frozen fintech.ebics>", line 115, in urlopen
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1442, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 694, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 327, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'ebics.zkb.ch' doesn't match either of '*.odoo.com', 'odoo.com'
```

**Comment by luc-demeyer** [comment]
@NMisko 
I suggest we setup a short conf call (with screen sharing) to have a closer look.
You can send me an e-mail to luc.demeyer@noviat.com to schedule this session.

**Comment by NMisko** [comment]
@luc-demeyer 
Sorry for the slow response, I'm trying to get a meeting set up from our side. You should get an email today or tomorrow.

**Comment by joonis** [comment]
Please update PyFinTech to version 6.5.
Fixed missing TLS SNI support.

**Comment by joonis** [comment]
Hmm... but why did you get a certificate from Odoo?
```
ssl.CertificateError: hostname 'ebics.zkb.ch' doesn't match either of '*.odoo.com', 'odoo.com'
```

**Comment by NMisko** [comment]
This was unfortunately a misconfiguration on our side, we just set the wrong ebics host url. So, there's no issue with this module or fintech.
