### ISSUE TITLE
Unknown key format error in 'Get Bank Keys' step (ebics_init_3) 

### ISSUE THREAD

**Issue by NMisko** [Noviat/account_ebics#22]
I'm getting this error when trying to 'Get Bank Keys' for a user. Do you know what this could be due to? Once again I'm having a hard time debugging it, due to not having the fintech source.

The key file has the following format (keys replaced by `----`):
```
{
  "#USER": {
    "A": {
      "certs": [],
      "key": "----",
      "version": "A006"
    },
    "E": {
      "certs": [],
      "key": "----",
      "version": "E002"
    },
    "X": {
      "certs": [],
      "key": "----",
      "version": "X002"
    }
  }
}
```
The keys have 1668 characters, the only special characters being `+` and `/`.

```
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/account_ebics/models/ebics_userid.py", line 391, in ebics_init_3
    userid=self.name)
  File "<string>", line 1, in <lambda>
  File "<frozen fintech>", line 411, in _checkparams
  File "<frozen fintech.ebics>", line 1021, in __init__
  File "<string>", line 1, in <lambda>
  File "<frozen fintech>", line 411, in _checkparams
  File "<frozen fintech.ebics>", line 759, in __getitem__
  File "<frozen fintech.ebics>", line 347, in __init__
ValueError: unknown key format
```

**Comment by luc-demeyer** [comment]
Did you check if your bank supports A006 (RSASSA-PSS) ?

**Comment by CarlHerkommermuch** [comment]
Hi @luc-demeyer,

we checked with our bank, they said they support A006

Regards,
Carl

**Comment by luc-demeyer** [comment]
Contact me via luc.demeyer@noviat.com to setup a short conf call with screen sharing so that I can have a look to setup, Odoo log file and odoo keys file.

**Comment by joonis** [comment]
The error comes from PyFinTech. There is definitely something wrong with the key data.

**Comment by NMisko** [comment]
We aren't 100% sure, but we believe this issue is likely due to some missing authorization from the bank, but we still have to look into this. Will close this as soon as we are sure this was it.

**Comment by luc-demeyer** [comment]
@CarlHerkommermuch 
can this issue be closed in the meanwhile ?
