### ISSUE TITLE
SSLCertVerificationError with Odoo 11 and Python 3.7

### ISSUE THREAD

**Issue by olivierb2** [Noviat/account_ebics#4]
Hello,

I recently migrated my Odoo to version 11, including using Debian Buster and Python 3.7. I'm not sure if this is related to fintech module, but Downloading CAMT file with my bank gives this error. I'm using account_ebisc version from Github.

Unknown Error
Traceback (most recent call last):
  File "/opt/odoo/addons/account_ebics/wizard/ebics_xfer.py", line 177, in ebics_download
    data = method(**kwargs)
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<frozen fintech>", line 221, in _call
  File "<frozen fintech>", line 419, in _checkparams
  File "<string>", line 1, in <lambda>
  File "<frozen fintech>", line 221, in _call
  File "<frozen fintech.ebics>", line 2321, in C53
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<frozen fintech>", line 221, in _call
  File "<frozen fintech>", line 419, in _checkparams
  File "<string>", line 1, in <lambda>
  File "<frozen fintech>", line 221, in _call
  File "<frozen fintech.ebics>", line 1839, in download
  File "<string>", line 1, in <lambda>
  File "<frozen fintech>", line 221, in _call
  File "<frozen fintech.ebics>", line 3098, in send
  File "<frozen fintech.ebics>", line 194, in urlopen
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "<frozen fintech.ebics>", line 183, in https_open
ssl.SSLCertVerificationError: ('1056)',)

**Comment by olivierb2** [comment]
It seems that issue is coming from an issue with OpenSSL version check. It seems solved by updating the file `/etc/ssl/openssl.cnf`and updating as follow.

     [system_default_sect]
     MinProtocol = TLSv1.0
     CipherString = DEFAULT@SECLEVEL=2
