### ISSUE TITLE
Issue downloading CAMT with Odoo 11

### ISSUE THREAD

**Issue by olivierb2** [Noviat/account_ebics#5]
Dear support,

I have the issue when new files are available in my bank. For some reason, the file is downloaded, but Odoo give me this message.

Traceback (most recent call last):
  File "/opt/odoo/addons/account_ebics/wizard/ebics_xfer.py", line 178, in ebics_download
    ebics_files += self._handle_download_data(data, df)
  File "/opt/odoo/addons/account_ebics/wizard/ebics_xfer.py", line 424, in _handle_download_data
    data[doc], file_format, docname=doc)
  File "/opt/odoo/addons/account_ebics/wizard/ebics_xfer.py", line 473, in _create_ebics_file
    % fn)
odoo.exceptions.UserError: ("EBICS File with name 'CSEBICS_CAMT053_CH_04_WDS_6584767_0266-1590778-12-000_20190514_010013_001.xml.c53.xml' has already been downloaded.\nPlease check this file and rename in case there is no risk on duplicate transactions.", '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/account_ebics/wizard/ebics_xfer.py", line 201, in ebics_download
    self.note += e.message
AttributeError: 'UserError' object has no attribute 'message'

**Comment by luc-demeyer** [comment]
Olivier,

https://github.com/Noviat/account_ebics/pull/6 will create a more readible error message.
Hence please update your account_ebics repo.

The real issue is that you try download a camt statement that has already been downloaded.
Normally the bank keeps track of the latest downloaded statement and hence you don't get duplicates.
In order to fix this, you can rename the duplicate file on your system (cf. Ebics Files) or alternatively skip it by using a more recent date range for the download.

But you also need to ensure that the donwload operations is completed succesfully between Odoo and the bank so that your bank doesn't present a duplicate statement.
I have seen this behaviour before when running the 'eval' version of the prereq FinTech software. If this is the case, you should contact joonis.de to obtain the license keys for your system.
